/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMe"];
        trace?: never;
    };
    "/v1/me/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyActivities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateEvent"];
        trace?: never;
    };
    "/v1/events/{eventId}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEventApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{eventId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{eventId}/participation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["joinEvent"];
        post?: never;
        delete: operations["leaveEvent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{eventId}/applications/{participationId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["decideEventApplication"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example user@example.com */
            email: string;
            password: string;
            /**
             * Format: date
             * @example 2000-05-17
             */
            birthDate: string;
        };
        SessionUserDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** Format: date */
            birthDate: string;
            /** @default false */
            showAge: boolean;
            /** @default false */
            onboardingCompleted: boolean;
        };
        SessionEnvelopeDto: {
            sessionToken: string;
            /** Format: date-time */
            expiresAt: string;
            user: components["schemas"]["SessionUserDto"];
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            password: string;
        };
        CityDto: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            timeZone: string;
        };
        CategoryDto: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
        };
        MeDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** Format: date */
            birthDate: string;
            displayName?: string | null;
            /** @default false */
            showAge: boolean;
            avatarUrl?: string | null;
            bio?: string | null;
            city?: components["schemas"]["CityDto"] | null;
            interests: components["schemas"]["CategoryDto"][];
            onboardingCompleted: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MyParticipationDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "pending" | "going" | "rejected" | "withdrawn" | "cancelled";
            seenEventVersion: number;
            hasEventUpdates: boolean;
        };
        ActivityItemDto: {
            /** Format: uuid */
            id: string;
            title: string;
            category: components["schemas"]["CategoryDto"];
            city: components["schemas"]["CityDto"];
            meetingPlace: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt?: string | null;
            imageUrl?: string | null;
            /** @enum {string} */
            participationMode: "automatic" | "approval_required";
            participantsCount: number;
            capacity: number;
            isFull: boolean;
            /** @enum {string} */
            status: "published" | "cancelled";
            contentVersion: number;
            myParticipation?: components["schemas"]["MyParticipationDto"] | null;
            hasEventUpdates: boolean;
            availableActions: string[];
            pendingApplicationsCount?: number | null;
        };
        ActivitiesListDto: {
            items: components["schemas"]["ActivityItemDto"][];
            nextCursor?: string | null;
        };
        PatchMeDto: {
            displayName?: string;
            showAge?: boolean;
            bio?: string | null;
            /** Format: uuid */
            cityId?: string;
            categoryIds?: string[];
        };
        CreateEventDto: {
            title: string;
            /** Format: uuid */
            categoryId: string;
            description: string;
            /** Format: uuid */
            cityId: string;
            meetingPlace: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt?: string | null;
            capacity: number;
            /** @enum {string} */
            participationMode: "automatic" | "approval_required";
        };
        ParticipantDto: {
            /** Format: uuid */
            id: string;
            displayName: string;
            avatarUrl?: string | null;
            age?: number;
        };
        EventDetailsDto: {
            /** Format: uuid */
            id: string;
            title: string;
            category: components["schemas"]["CategoryDto"];
            city: components["schemas"]["CityDto"];
            meetingPlace: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt?: string | null;
            imageUrl?: string | null;
            /** @enum {string} */
            participationMode: "automatic" | "approval_required";
            participantsCount: number;
            capacity: number;
            isFull: boolean;
            /** @enum {string} */
            status: "published" | "cancelled";
            contentVersion: number;
            description: string;
            organizer: components["schemas"]["ParticipantDto"];
            participants: components["schemas"]["ParticipantDto"][];
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            myParticipation?: components["schemas"]["MyParticipationDto"] | null;
            availableActions: string[];
        };
        EventSummaryDto: {
            /** Format: uuid */
            id: string;
            title: string;
            category: components["schemas"]["CategoryDto"];
            city: components["schemas"]["CityDto"];
            meetingPlace: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt?: string | null;
            imageUrl?: string | null;
            /** @enum {string} */
            participationMode: "automatic" | "approval_required";
            participantsCount: number;
            capacity: number;
            isFull: boolean;
            /** @enum {string} */
            status: "published" | "cancelled";
            contentVersion: number;
        };
        EventListDto: {
            items: components["schemas"]["EventSummaryDto"][];
            nextCursor?: string | null;
        };
        EventApplicationDto: {
            /** Format: uuid */
            id: string;
            applicant: components["schemas"]["ParticipantDto"];
            /** @enum {string} */
            status: "pending" | "going" | "rejected" | "withdrawn" | "cancelled";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            statusChangedAt: string;
        };
        EventApplicationListDto: {
            items: components["schemas"]["EventApplicationDto"][];
        };
        UpdateEventDto: {
            expectedVersion: number;
            title?: string;
            /** Format: uuid */
            categoryId?: string;
            description?: string;
            /** Format: uuid */
            cityId?: string;
            meetingPlace?: string;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string | null;
            capacity?: number;
            /** @enum {string} */
            participationMode?: "automatic" | "approval_required";
        };
        JoinEventDto: {
            participation: components["schemas"]["MyParticipationDto"];
            participantsCount: number;
            capacity: number;
            isFull: boolean;
        };
        ApplicationDecisionDto: {
            /** @enum {string} */
            decision: "approve" | "reject";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelopeDto"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelopeDto"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchMeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    getMyActivities: {
        parameters: {
            query?: {
                tab?: "upcoming" | "applications" | "created" | "past" | "cancelled";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitiesListDto"];
                };
            };
        };
    };
    listCities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityDto"][];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"][];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query: {
                cityId: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListDto"];
                };
            };
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailsDto"];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailsDto"];
                };
            };
        };
    };
    updateEvent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailsDto"];
                };
            };
        };
    };
    listEventApplications: {
        parameters: {
            query?: {
                status?: "pending" | "going" | "rejected" | "withdrawn" | "cancelled";
            };
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventApplicationListDto"];
                };
            };
        };
    };
    cancelEvent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailsDto"];
                };
            };
        };
    };
    joinEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinEventDto"];
                };
            };
        };
    };
    leaveEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinEventDto"];
                };
            };
        };
    };
    decideEventApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
                participationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationDecisionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinEventDto"];
                };
            };
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
